settings:
  flimit: 1000

schema:
# ######################################################################################################################
- name: "COR"
  path: "./cmd/corteza"
  commands: { run: { status: true } }
  args: [ "serve-api" ]
  watcher:
    paths: [ "../" , "../../system" , "../../messaging" , "../../compose" , "../../pkg" , "../../corteza" , "../../app" ]
    extensions: [ "go" ]
    ignored_paths: [ "../../vendor", "../../.git" ]
